require: rubocop-rails

AllCops:
  Exclude:
    - "bin/*"
    - "db/**/schema.rb"
    - "db/migrate/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "db/migrate/**/*"

Layout/LineLength:
  Exclude:
    - "config/initializers/*"
